version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    versioning-strategy: auto
    labels:
      - "dependencies"
      - "javascript"
      - "security"
    assignees:
      - "AI-Empower-HQ-360"
    reviewers:
      - "AI-Empower-HQ-360"
    groups:
      test-dependencies:
        patterns:
          - "jest*"
          - "@testing-library/*"
          - "@playwright/*"
      react-dependencies:
        patterns:
          - "react*"
          - "@emotion/*"
          - "@tanstack/*"
    
  # Enable version updates for Python
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "python"
      - "security"
    assignees:
      - "AI-Empower-HQ-360"
    reviewers:
      - "AI-Empower-HQ-360"
    groups:
      flask-dependencies:
        patterns:
          - "flask*"
          - "werkzeug"
      test-dependencies:
        patterns:
          - "pytest*"
          - "black"
          - "flake8"
      database-dependencies:
        patterns:
          - "sqlalchemy*"
          - "psycopg2*"
          - "redis*"
    
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "github-actions"
      - "security"
    assignees:
      - "AI-Empower-HQ-360"
    reviewers:
      - "AI-Empower-HQ-360"
