#!/bin/bash

echo "📋 DURABLE DEPLOYMENT INSTRUCTIONS"
echo "=================================="
echo ""
echo "1. Get your API URL from Cloud Shell Web Preview (port 5000)"
echo "2. Edit the files in durable-deployment/ folder"
echo "3. Replace 'YOUR_API_URL_HERE' with your actual URL"
echo "4. Copy the content and paste in Durable"
echo ""
echo "FILES CREATED:"
echo "- index.html (Full standalone version)"
echo "- durable-widget.html (Widget for embedding)"
echo ""
echo "📝 NEXT STEPS:"
echo "1. Go to durable.co and edit empowerhub360.org"
echo "2. Find 'Add Section' → 'Custom Code' or 'HTML Block'"
echo "3. Copy content from durable-widget.html"
echo "4. Replace YOUR_API_URL_HERE with your Cloud Shell URL"
echo "5. Save and publish!"
echo ""
echo "🚀 Your spiritual platform will be live on empowerhub360.org!"
