version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DEBUG=True
      - SECRET_KEY=dev_key_change_in_production
    volumes:
      - .:/app
    restart: unless-stopped

  # Uncomment to add a database service
  # db:
  #   image: postgres:13
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=heartdb
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped

# Uncomment to add a database service
# volumes:
#   postgres_data:
