name: Dependency Updates

on:
  schedule:
    - cron: '0 0 * * 1'  # Run weekly on Monday at midnight
  workflow_dispatch:  # Allow manual triggers

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Update npm dependencies
        run: |
          npm outdated || true
          npm update
          npm audit fix

      - name: Update Python dependencies
        run: |
          cd backend
          pip list --outdated
          pip install -r requirements.txt --upgrade
          pip freeze > requirements.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(deps): update dependencies"
          title: "⬆️ Update Dependencies"
          body: |
            This PR updates project dependencies to their latest compatible versions.
            
            Please review the changes and test thoroughly before merging.
          branch: "deps/update-dependencies"
          labels: "dependencies,automated pr"
          assignees: "AI-Empower-HQ-360"
          reviewers: "AI-Empower-HQ-360"
